### ISSUE TITLE
Please upload your dashboard into the repo

### ISSUE THREAD

**Issue by firasm** [ubco-W2022T2-data301/project-group-group48#14]
Hello,

@sairafurqan and I are grading your project and noticed that your dashboard files are not uploaded to the project repo. Could you please do this ASAP so everything is all in one place?

Thanks!

Dr. Moosvi

**Comment by t0bi4** [comment]
Hi, I put my dashboard things in the dashboard folder.

**Comment by Alvintheboi** [comment]
HI i also put my dashboard in the folder now.

**Comment by ngaranna** [comment]
Hello Dr. Moosvi,

I had trouble getting my student status verified when I first downloaded
Tableau so I just did a 14-day trial. Now that my trial has ended, I am
having complications opening my dashboard and I keep receiving an error
message that there is a problem connecting to my data sources. I have now
exported and uploaded my Tableau file as is, please let me know if you can
open it on your end.

Kind regards,
Annabelle

**Comment by firasm** [comment]
Thanks

**Comment by firasm** [comment]
@t0bi4 - we need to see your `.twbx` file in the dashboards folder not just a PNG!

https://github.com/ubco-W2022T2-data301/project-group-group48/tree/main/dashboard

**Comment by t0bi4** [comment]
Hi professor, 
Apologies for the late response. I tried to recover my tableau that I saved unto my computer but it did not save and now I do not have access to it. The only thing I was able to recover was the png. I'm not sure if that will affect our grade and my apologies. I can try and recreate the file if that would be easier but it might take me some time as I am currently studying for exams. Please let me know what you would prefer me to do. 

Thank you 

Tobi

**Comment by firasm** [comment]
Hi Tobi,

This is extremely unfortunate, this is why we tried to teach you throughout the course to commit and push your work frequently (including binary files like Tableau). Given how late it is in the term, we'll grade your Tableau dashboard by looking at your video and give you the benefit of the doubt that you learned the skills we expected you to.

**Comment by t0bi4** [comment]
Thank you very much, again, my apologies for the inconvenience.
